### ISSUE TITLE
Tiny titlebar closing button on hidpi

### ISSUE THREAD

**Issue by aquatix** [solus-project/evopop-gtk-theme#30]
On my Dell XPS 15 with 3200x1800 screen, evopop looks phenomenal. I love how it looks and feels. Only minor gripe I have is that the close button in regular window bars is tiny. It's about a quarter of the size of the version in Nautilus and such, so it seems it isn't using a highres version. This makes it look rather off, as it isn't centered too because of that.

I'm attaching a screenshot with what I mean.

**Comment by aquatix** [comment]
![Difference between combined title bar and regular one with tiny button](https://cloud.githubusercontent.com/assets/629545/6992296/487f5bdc-dac6-11e4-87e1-d79e18d2706c.png)

**Comment by poltertec** [comment]
will see what i can do about this.
Which version of Gtk/Mutter are you running on?

**Comment by aquatix** [comment]
Gtk version 3.14.4, Mutter 3.14.3 (Ubuntu Gnome 14.10 with gnome-staging ppa).

**Comment by poltertec** [comment]
Any change you could try out a 3.16 distro build in vm or wathever?
What i have read about it so far support in mutter for this has only been added since 3.16

**Comment by aquatix** [comment]
Hey, sorry to have been silent for so long. I can't get it working in a VM, as Virtualbox doesn't recognise being on a hidpi screen (so everything is just tiny, or upscaled like you can do with the "Window scaling" setting in Gnome Tweak.

Also, all livecd's (usb's) somehow are against me, as they refuse to boot on this machine. I'll try again later this weekend.

**Comment by aquatix** [comment]
OK, finally have Gnome 3.16 on this machine and the buttons seem to be fine, size-wise (see attachment). Only thing that is different, is that the on-hover change from red to red-with-cross has gone; it's now always red-with-cross. This still works correctly in programs like Nautilus.

![screenshot from 2015-04-26 08-32-13](https://cloud.githubusercontent.com/assets/629545/7336176/036fc786-ebef-11e4-95b5-db0ec799b4e0.png)

**Comment by poltertec** [comment]
hmm wierd,

mutter is now (3.16) controlled by gtk+ so should be the same as nautilus, etc
Will investigate :)

**Comment by aquatix** [comment]
Well, apparently it was an environment issue: both on Arch and Ubuntu Gnome 15.04 (with 3.16 from ppa's), GDM was started twice (!), which resulted in this artifact. I fixed it by adding FirstVT=7 to /etc/gdm/custom.conf, which makes GDM only run once (I hope). Your theme now works as it should :)

**Comment by poltertec** [comment]
Allright nice to hear :)
