### ISSUE TITLE
Add Nautilus sidebar colour

### ISSUE THREAD

**Issue by sergioad** [solus-project/evopop-gtk-theme#32]
Hello @poltertec I noted that Nautilus has not a colored sidebar, the sidebar has a white colour as the content box (the place where are the folders and files of your visited directory) and this mamkes the sidebar look as another content box can you make it look more like a panel using the same grey of the  panel but a little bit lighter?

**Comment by poltertec** [comment]
Hey,

Actually tried that but didn't work.
Had something else planned but a bug in gtk is holding it back.
However i will look for a temp solution.

**Comment by sergioad** [comment]
Ok, thank you very much, seeing Evopop with the Nautilus sidebar and symbolic window controls variant will be AMAZING, if I find this I will use Evopop each day :smile:
