### ISSUE TITLE
[REQUEST] Symbol only window controls variant

### ISSUE THREAD

**Issue by sergioad** [solus-project/evopop-gtk-theme#33]
Hello @poltertec I love EvoPop but I do not like it's Mac OSX like circled window controls, can you add a variant of the EvoPop dark and light themes but with symbolic window controls? instead of the three circles of diferent they should be a - + and x symbols coloured in black and when pressed them should change to red (for close) blue (for maximize) and green (for minimize), exactly the same colours used by the coloured circle window controls

I know that is many work but I think the result will be AMAZING :smile:

**Comment by poltertec** [comment]
Hey,
Will certainly add this at some point, however not atm to keep it manageable.

**Comment by sergioad** [comment]
Thank you very much, I love Evopop but certainly the Mac OSX like window controls are not for me :smile:

**Comment by poltertec** [comment]
temp url https://github.com/poltertec/basepop-gtk-theme
