### ISSUE TITLE
Borders on Nautilus List view [316]

### ISSUE THREAD

**Issue by alex285** [solus-project/evopop-gtk-theme#35]
See screenshot
[borders-evopop-list-view](https://cloud.githubusercontent.com/assets/11244308/7098325/db511d30-dfe7-11e4-8caf-dd12e8de5483.png)

**Comment by poltertec** [comment]
can't recreate on our testbuild but will try to fix this, this weekend.

**Comment by alex285** [comment]
If you dont have 316, I can fix for you, but after monday

**Comment by poltertec** [comment]
We do have 316 in testing but the prob doesn't show up.
However have to install an other distro to test an other problem anyways so no worries :)

**Comment by alex285** [comment]
You can do this:
NautilusListView GtkTreeView {
	border-top:1px solid #E6E8EB; //your border color	
}
