### ISSUE TITLE
Some Apps BG Is Not Rendered Properly. (Border Shadow)

### ISSUE THREAD

**Issue by Abhishek-Rawal** [solus-project/evopop-gtk-theme#36]
![screenshot from 2015-04-11 09-07-19](https://cloud.githubusercontent.com/assets/10757422/7100109/d550c186-e02a-11e4-95ff-cef5344b8fbb.png)

Some apps like 'Terminal' 'Sublime Text 3' have weird border shadow.
While most apps just looks perfect.
I have compared Terminal (which shows weird background shadow) with Nautilus (which is delivering bg shadow perfectly)

Gnome 3.16.0
ArchLinux

**Comment by poltertec** [comment]
Something to do with metacity will look into it this weekend.
