### ISSUE TITLE
Popover arrows sizes

### ISSUE THREAD

**Issue by alex285** [solus-project/evopop-gtk-theme#38]
I wanna keep a consistency on some elements like popover arrows. Are you gonna keep this size?
I think it hasn't a "smooth" height/width ratio. On Shell I use base 16 rise 7, which a "copy" from Google plus notifications. 
Bootstrap dropped arrows on popovers when there arrow indicators on buttons, which is the same as in GNOME Shell. Should I completely drop arrows?
Ideas?  

![arrows](https://cloud.githubusercontent.com/assets/11244308/7102362/df78b6b2-e086-11e4-81c0-ee79f49eab98.png)

**Comment by alex285** [comment]
Irrelevant but the cogl button (Settings) should be replaced with a menu button. It's 3.16 change if I can recall.

**Comment by poltertec** [comment]
I'm fine with switching to base 16 rise 7

Grtz

**Comment by alex285** [comment]
Great! Closing this, I open another for the cogl/gear menu later. Thanks!
