### ISSUE TITLE
Fuzzy upscaled slide buttons on hidpi

### ISSUE THREAD

**Issue by aquatix** [solus-project/evopop-gtk-theme#42]
Hey, another hidpi bug, sorry :)

Almost all gtk widgets look great and sharp on my 3200x1800 screen (XPS15) in Gnome 3.14, except for the enable/disable slide toggles (see attachment). They seem to get upscaled from regular-dpi versions.

I'll also try to test this in 3.16 later this weekend (like #30), but I guess this is some assets thing?

Thanks in advance!

![screenshot from 2015-04-18 13 26 29](https://cloud.githubusercontent.com/assets/629545/7215240/d688aec0-e5ce-11e4-88c6-429f16826343.png)

**Comment by poltertec** [comment]
Yep noticed that is same in 3.16.
Kind of a bugger since they are liniar drawings.
Still searching how best to solve this.
Grtz

**Comment by aquatix** [comment]
Ah, bugger...

Anyway, they don't bother me much, so take your time thinking how to fix it properly. If I can help (test), please let me know!

**Comment by poltertec** [comment]
I'll have the hidpi fixed this weekend.
Only 3.14 metacity window controls wont work could probally solve that by making a seperate package for it.
