### ISSUE TITLE
Unreadable buttons in Geary

### ISSUE THREAD

**Issue by aenima1985** [solus-project/evopop-gtk-theme#43]
I'm on Arch + Gnome 3.16, "show images" button are unreadable but "hover" effect is ok.

![screenshot from 2015-04-21 19-58-05](https://cloud.githubusercontent.com/assets/11461117/7259193/f70413ac-e861-11e4-9840-3d70fd333974.png)
![buttons](https://cloud.githubusercontent.com/assets/11461117/7259286/93cb34cc-e862-11e4-964c-c9d0eaa45c4b.png)

**Comment by poltertec** [comment]
seems to be a bug in geary itself.
Uses the .button:active color setting in all states while background-color does change.
