### ISSUE TITLE
Window control symbols swapped in CSD apps

### ISSUE THREAD

**Issue by Deminarcis** [solus-project/evopop-gtk-theme#45]
When opening CSD apps in Unity , the symbols for minimize and maximize are switched. the color and function are correct , but the symbol is swapped .

OS: Ubuntu 15.04
i am using the latest published tar of evopop ( 0.26)

![selection_567](https://cloud.githubusercontent.com/assets/7146314/7511545/eab3d5f4-f4e8-11e4-9211-fe45541a958b.png)

**Comment by poltertec** [comment]
Hey will try to look in to it this weekend however, very busy atm with new job, etc

**Comment by poltertec** [comment]
just installed ubuntu myself.
The unity icons are wrong actually and some other stuff needs work in there aswell.
For all to work properly however gtk 3.16 is required, which isn't coming to ubuntu anytime soon unfortunately.

**Comment by poltertec** [comment]
i'm dropping gtk3.14 & unity support on this theme.
However i made a fork with normal window controls in which unity will be easier to support.
temp url: https://github.com/poltertec/basepop-gtk-theme
