### ISSUE TITLE
Windows control buttons not visible on the theme

### ISSUE THREAD

**Issue by Abhinav1217** [solus-project/evopop-gtk-theme#48]
Last night I updated the evopop theme by issuing following commands as root user in gnome-terminal.
` # git pull origin master`
` # sh ./autogen.sh`
` # make install`

After this I used Gnome-Tweak-Tool to select GTK+ theme and Windows theme to Evopop.  First thing I noticed was that now it was not listed on the Windows dropdown.  Then I noticed that Minimize, Maximize and Close button are not visible. However if I click it the approximate location of those button, I can close or minimize the window. 

I tried a clean install by deleting the /usr/share/theme/evopop-* folders,  and a fresh git clone, Still the same. 

How do I get the theme back 

***Windows control buttons not visible on the theme***
![Windows control buttons not visible on the theme](https://cloud.githubusercontent.com/assets/740584/7664973/4beb238a-fbc0-11e4-9fef-3037f412a432.png)

***Evopop is not listed in the windows dropdown.***
![Evopop is not listed in the windows dropdown](https://cloud.githubusercontent.com/assets/740584/7664961/d326781e-fbbf-11e4-95fa-eb604feec625.png)

**EDIT ::**  
Forgot to tell  I am using Fedora 21

**Comment by alex285** [comment]
@Abhinav1217 perhaps that happened after Evopop dropped 314 support. 
https://github.com/solus-project/evopop-gtk-theme/commit/2b6b2693586b22cb21120ffa588f95ca3f58521b

**Comment by Abhinav1217** [comment]
Perhaps ...  I shall test it on VM on Fedora 22 beta to be sure.

**Comment by poltertec** [comment]
Yepz window controls are controlled differently and more accurate since 3.16.
Which evopop requires to work properly, since every setup requires diffrent coding in 3.14 i gave that one up.
