### ISSUE TITLE
Buttons do not theme properly in chromium

### ISSUE THREAD

**Issue by abrouwers** [solus-project/evopop-gtk-theme#51]
Hi!

Just giving the theme a shot, and love it!  Unfortunately, I noticed that the buttons are not being themed properly in chromium - attached is a SS showing a hover over a button.

I know that chromium is a strange beast, but it seems to work OK with adwaita, so hopefully it's fixable!  I just updated to git (2015-05-24), and the issue persists.

Thanks for your work.
![screenshot from 2015-05-24 10-48-42](https://cloud.githubusercontent.com/assets/30065/7788286/85d2ac7e-0202-11e5-8be4-d68a3bcae7e4.png)

**Comment by poltertec** [comment]
Works fine here, is the gtk2 murrine engine installed?

**Comment by abrouwers** [comment]
Sorry, completely my fault!  I didn't notice it as a dep, as I was mostly focused on the GTK3 version.

**Comment by poltertec** [comment]
no problem happy it's resolved :)
