### ISSUE TITLE
Firefox tooltip issue

### ISSUE THREAD

**Issue by meghprkh** [solus-project/evopop-gtk-theme#53]
The tooltips have a transparent background and in many cases I cant read them.
(Fedora 22 and Firefox 38.0.1)

![screenshot from 2015-06-01 22-47-05](https://cloud.githubusercontent.com/assets/5979605/7918609/3948d090-08b0-11e5-933f-aa0a7ddaa3e3.png)

**Comment by meghprkh** [comment]
Another issue is with the downloading progress bar. (The sppinner appears over the progress bar but that is Adwaita bug also) but the background of progress bar is not blue.
![screenshot from 2015-06-01 22-51-32](https://cloud.githubusercontent.com/assets/5979605/7918688/eb60415a-08b0-11e5-9d5e-1689d220ea4e.png)

**Comment by poltertec** [comment]
Tooltip issue should be fixed will look into progressbar later.
