### ISSUE TITLE
Broken Firefox 38 widgets

### ISSUE THREAD

**Issue by joca-bt** [solus-project/evopop-gtk-theme#55]
I'm using GNOME 3.16 with the EvoPop theme under Arch Linux and Firefox's widgets are broken as shown here http://imgur.com/Dpjt1JC. For example, when I click in any widget there's no visual feedback: the widgets seem to be empty all the time, although they're not. Also, button widgets do not seem to be using the EvoPop theme. Other themes, e.g. Adwaita, do not have these issues.

**Comment by nlaplante** [comment]
:+1: same here. Firefox 38.0.5

**Comment by joca-bt** [comment]
Changed to Firefox 39, still happening. I noticed this also with some other applications so perhaps some base themings are missing.

**Comment by ikeydoherty** [comment]
You're missing the correct gtk2 engines packages. Likely murrine + pixbuf, not actually checked myself.

**Comment by joca-bt** [comment]
Thanks, I also thought it could be some missing packages, but had no idea which ones. I will try it later today.

**Comment by joca-bt** [comment]
Duh, I'm an idiot "This project is still a work in progress. Requires Gtk 3.16 & gtk-engine-murrine to function properly.". I'll ask for the AUR package to be upgraded to list that as a dependency.

**Comment by joca-bt** [comment]
The AUR package has been updated.
