### ISSUE TITLE
Depricated issues in Fedora 25

### ISSUE THREAD

**Issue by Abhinav1217** [solus-project/evopop-gtk-theme#66]
I have cloned this repo and installed evopop-gtk-theme in fresh installed Fedora 25.
 
On launching apps using terminal, multiple depricated issues are shown.
It all boils down to 3 errors, "One color stop", "not a number", "Expected a string". 
I tried in multiple default apps like nautilus, firefox, and also on apps installed by me such as fedy.

```
Theme parsing error: gtk.css:500:70: Using one color stop with linear-gradient() is deprecated.

(gjs:17817): Gtk-WARNING **: Theme parsing error: gtk.css:513:70: Using one color stop with linear-gradient() is deprecated.

(gjs:17817): Gtk-WARNING **: Theme parsing error: gtk.css:584:72: Using one color stop with linear-gradient() is deprecated.

(gjs:17817): Gtk-WARNING **: Theme parsing error: gtk.css:591:12: not a number

(gjs:17817): Gtk-WARNING **: Theme parsing error: gtk.css:591:12: Expected a string.
```
These error were not present when using older solus-cold-storage repo, which workes fine with few glitches in F25

**Comment by Abhinav1217** [comment]
Anything??

**Comment by D4v2z** [comment]
Hi, Did you get it installed? I have F25 and with the script './install-gtk-theme.sh' everything ok, have you tried './install-geary-fix.sh' ?

**Comment by Abhinav1217** [comment]
I installed it by downloading from github and running  the script. I don't use geary so I haven't run the fix.

**Comment by poltertec** [comment]
Working on it atm.
Srry for the late response, been busy with work and other life projects :)

**Comment by poltertec** [comment]
Should be resolved :)
