### ISSUE TITLE
Menu bar has the text with the same color as the background

### ISSUE THREAD

**Issue by carloswbarros** [solus-project/evopop-gtk-theme#68]
The menu bar has the text with the same color as the background, this doesn't happen to every application. If I hover the menu item, I can see the text of that menu item.

Transmission:
![screenshot from 2017-07-02 13-41-42](https://user-images.githubusercontent.com/2727733/27769912-fe3c31a6-5f2c-11e7-9325-4be4fa099350.png)

Terminal:
![screenshot from 2017-07-02 13-41-13](https://user-images.githubusercontent.com/2727733/27769915-0619fd7c-5f2d-11e7-9025-f084c7374e5b.png)

Hovering the menu item:
(Somehow I can't screenshot while the menu is open :/)

KeepassX (Here it works):
![screenshot-20170702134829-941x71](https://user-images.githubusercontent.com/2727733/27769919-2f26559e-5f2d-11e7-96d3-720e5647e8da.png)

My gnome-tweak:
![screenshot-20170702135404-449x322](https://user-images.githubusercontent.com/2727733/27769951-f5a610ec-5f2d-11e7-9a58-211793b7a71d.png)

I'm using **Ubuntu Gnome 17.04** and **GNOME Shell** version is **3.24.2**.

What the problem might be?

**Comment by poltertec** [comment]
thx problem found has something to do with the budgie theming.
Hope to push it tomorrow, atm still working on a extra color sheme.
