### ISSUE TITLE
dark font colour on panel

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/evopop-gtk-theme#69]
![workspace 1_074](https://user-images.githubusercontent.com/996240/29498035-f753aa1e-85eb-11e7-9f97-3034f7167955.jpg)

Using evopop preview 2.9.92 on Ubuntu 17.04 (GTK+ 3.22) without the dark-theme checked.

The font colour of the clock applet and the global menu applet is very dark; intentional?

Fonts are Noto Sand UI Bold

**Comment by poltertec** [comment]
Not really :s 
Fix inbound
